
import { DisciplineRecord, SchoolInfo } from './types';

export const SCHOOL_INFO: SchoolInfo = {
  name: "Maahad Tahfiz Al-Quran Ibnu Al-Jazari",
  address: "Jalan Masjid, Kampung Beringis 89600 Papar, Sabah",
  phone: "019-8898417",
  email: "mtij.edu@gmail.com"
};

export const STUDENT_NAMES: string[] = [
  "Muhammad Aniq Syahmi bin Roslee",
  "Muhammad Hadi Haziq bin Abdul Jain",
  "Muhammad Zaheerul Adam Bin Halidin",
  "Abdul Lathif Qayyum Bin Abdurahman",
  "Muhammad Muazzam Luthfi Bin Rosdi",
  "Awangku Haziq Khairuddin Bin Hashim",
  "Mohd Khairil Faizi Bin Moktar",
  "Muhammad Hariz Mustaqim Bin Junhiniedian",
  "Muhammad Syurhabil Bin Samsudin",
  "Muhammad Habil Bin Rody",
  "Muhammad Toha Bin Muhammad",
  "Hafizh Azhar Bin Saiful Suriano",
  "Mohammad Rezky Adha Bin Mohd Hazrollah",
  "Muhammad Salahuddin Al Hafiz Bin Adsmil",
  "Muzhafar Ikram Bin Irwan",
  "Qayyim Bin Alimmudin",
  "Ahmad Fitri Husaini Bin Muhammad Firdaus",
  "Mohammad Hazimy Bin Abdullah",
  "Ashraf Firdaus Bin Faizal",
  "Muhammad Sarafudin Awang Sofrie Bin Abdullah",
  "Muhammad Deen Lc Bin Iqbal Lc",
  "Muhammad Ilfi Deen Bin Jasmi",
  "Muhammad Rayyan Azraq Bin Mohd Yaakub",
  "Muhammad Aqhil Furqon Bin Azizul"
];

export const CLASS_OPTIONS = ["ABU BAKAR", "UMAR", "UTHMAN"];
export const CATEGORY_OPTIONS = ["SALAH LAKU RINGAN", "SALAH LAKU SEDERHANA", "SALAH LAKU BERAT"];
export const LOCATION_OPTIONS = ["Kelas", "Dewan Makan", "Asrama", "Perkarangan MTIJ", "Ruang Dapur", "Surau", "Padang", "Lain-lain"];

export const VIOLATION_OPTIONS = [
  'Kurang adab terhadap guru (tanpa melawan secara terbuka)',
  'Membawa barang larangan',
  'Buang sampah merata-rata',
  'Keluar dari kawasan sekolah/asrama tanpa kebenaran pada waktu malam',
  'Menceroboh ruang dapur tanpa kebenaran',
  'Ponteng kelas',
  'Ponteng surau',
  'Tidak Berpakaian Kemas',
  'Gangguan Kelas',
  'Merokok/Vape',
  'Biadab terhadap Guru',
  'Lewat ke Madrasah',
  'Kekasaran Fizikal',
  'Lain-lain'
];

export const ACTION_OPTIONS = [
  'Amaran lisan',
  'Kaunseling',
  'Tindakan disiplin sekolah',
  'Tiada tindakan khusus',
  'Nasihat/Tazkirah',
  'Amaran Pertama',
  'Amaran Kedua',
  'Amaran Ketiga',
  'Gantung Sekolah',
  'Buang Sekolah',
  'Kerja Amal'
];

export const INITIAL_RECORDS: DisciplineRecord[] = [
  {
    id: "REC001",
    date: "2026-01-15",
    day: "Khamis",
    time: "11:30",
    studentName: "Muhammad Hariz Mustaqim Bin Junhiniedian",
    studentClass: "ABU BAKAR",
    category: "SALAH LAKU RINGAN",
    violationType: "Kurang adab terhadap guru (tanpa melawan secara terbuka)",
    demerit: -5,
    location: "Kelas",
    reportedBy: "Guru HEM",
    actionTaken: "Amaran lisan",
    details: "Ketika guru memberi nasihat, pelajar ini mengajuk-ngajuk percakapan guru",
    createdAt: 1736911800000
  },
  {
    id: "REC002",
    date: "2026-01-16",
    day: "Jumaat",
    time: "16:50",
    studentName: "Muhammad Syurhabil Bin Samsudin",
    studentClass: "ABU BAKAR",
    category: "SALAH LAKU RINGAN",
    violationType: "Membawa barang larangan",
    demerit: -5,
    location: "Dewan Makan",
    reportedBy: "Ustaz Sufi (warden)",
    actionTaken: "Amaran lisan",
    details: "Membawa meggi dan meletakkannya di bawah meja makan.",
    createdAt: 1736998200000
  },
  {
    id: "REC003",
    date: "2026-01-17",
    day: "Sabtu",
    time: "10:13",
    studentName: "Muhammad Habil Bin Rody",
    studentClass: "UMAR",
    category: "SALAH LAKU RINGAN",
    violationType: "Buang sampah merata-rata",
    demerit: -5,
    location: "Asrama",
    reportedBy: "Ustaz Sufi (warden)",
    actionTaken: "Amaran lisan",
    details: "Membuang sampah bawah katil",
    createdAt: 1737060780000
  },
  {
    id: "REC004",
    date: "2026-01-17",
    day: "Sabtu",
    time: "10:16",
    studentName: "Muhammad Habil Bin Rody",
    studentClass: "UMAR",
    category: "SALAH LAKU RINGAN",
    violationType: "Membawa barang larangan",
    demerit: -5,
    location: "Asrama",
    reportedBy: "Ustaz Sufi (warden)",
    actionTaken: "Amaran lisan",
    details: "bawa maggi",
    createdAt: 1737060960000
  },
  {
    id: "REC005",
    date: "2026-01-24",
    day: "Sabtu",
    time: "20:15",
    studentName: "Mohammad Rezky Adha Bin Mohd Hazrollah",
    studentClass: "UMAR",
    category: "SALAH LAKU BERAT",
    violationType: "Keluar dari kawasan sekolah/asrama tanpa kebenaran pada waktu malam",
    demerit: -20,
    location: "Perkarangan MTIJ",
    reportedBy: "Ustaz Sufi (warden)",
    actionTaken: "Amaran lisan",
    details: "Keluar dari sekolah pada waktu malam",
    createdAt: 1734700500000
  },
  {
    id: "REC006",
    date: "2026-01-24",
    day: "Sabtu",
    time: "20:00",
    studentName: "Muhammad Sarafudin Awang Sofrie Bin Abdullah",
    studentClass: "UTHMAN",
    category: "SALAH LAKU BERAT",
    violationType: "Keluar dari kawasan sekolah/asrama tanpa kebenaran pada waktu malam",
    demerit: -20,
    location: "Perkarangan MTIJ",
    reportedBy: "Ustaz Sufi (warden)",
    actionTaken: "Amaran lisan",
    details: "Keluar dari sekolah pada waktu malam",
    createdAt: 1737748800000
  },
  {
    id: "REC007",
    date: "2026-02-07",
    day: "Sabtu",
    time: "13:49",
    studentName: "Mohd Khairil Faizi Bin Moktar",
    studentClass: "ABU BAKAR",
    category: "SALAH LAKU RINGAN",
    violationType: "Menceroboh ruang dapur tanpa kebenaran",
    demerit: -5,
    location: "Ruang Dapur",
    reportedBy: "Nizam",
    actionTaken: "Tindakan disiplin sekolah",
    details: "Memasak tanpa pengatahuan staf lf atau guru.dan menguna barangan dapur untuk kegunaan peribadi",
    createdAt: 1738936140000
  },
  {
    id: "REC008",
    date: "2026-02-07",
    day: "Sabtu",
    time: "20:18",
    studentName: "Muhammad Muazzam Luthfi Bin Rosdi",
    studentClass: "UMAR",
    category: "SALAH LAKU RINGAN",
    violationType: "Menceroboh ruang dapur tanpa kebenaran",
    demerit: -5,
    location: "Ruang Dapur",
    reportedBy: "Nizam",
    actionTaken: "Tindakan disiplin sekolah",
    details: "Memasak tanpa izin staff atau guru dan mengunakan peralatan mahaad untuk kegunaan peribadi",
    createdAt: 1738959480000
  },
  {
    id: "REC009",
    date: "2026-02-07",
    day: "Sabtu",
    time: "13:56",
    studentName: "Muhammad Muazzam Luthfi Bin Rosdi",
    studentClass: "UMAR",
    category: "SALAH LAKU RINGAN",
    violationType: "Menceroboh ruang dapur tanpa kebenaran",
    demerit: -5,
    location: "Ruang Dapur",
    reportedBy: "Nizam",
    actionTaken: "Tindakan disiplin sekolah",
    details: "Memasak tanpa izin staff atau guru dan mengunakan barang dapur untuk kegunaan peribadi",
    createdAt: 1738936560000
  },
  {
    id: "REC010",
    date: "2026-02-08",
    day: "Ahad",
    time: "07:01",
    studentName: "Mohd Khairil Faizi Bin Moktar",
    studentClass: "UMAR",
    category: "SALAH LAKU SEDERHANA",
    violationType: "Ponteng kelas",
    demerit: -10,
    location: "Asrama",
    reportedBy: "Nizam",
    actionTaken: "Tindakan disiplin sekolah",
    details: "Alasan sakit kepala punca tidak dapat masuk kuliah pagi jam 7:00 am,tapi hanis saja kuliah langsung sehat.dan boleh main Bola.",
    createdAt: 1738998060000
  },
  {
    id: "REC011",
    date: "2026-02-10",
    day: "Selasa",
    time: "20:06",
    studentName: "Awangku Haziq Khairuddin Bin Hashim",
    studentClass: "ABU BAKAR",
    category: "SALAH LAKU RINGAN",
    violationType: "Ponteng surau",
    demerit: -5,
    location: "Asrama",
    reportedBy: "Nizam",
    actionTaken: "Kaunseling",
    details: "Berlari dan pura-pura tidur supaya tidak di suruh ke surau untuk solat berjemaah",
    createdAt: 1739217960000
  },
  {
    id: "REC012",
    date: "2026-02-10",
    day: "Selasa",
    time: "20:09",
    studentName: "Mohammad Hazimy Bin Abdullah",
    studentClass: "UMAR",
    category: "SALAH LAKU RINGAN",
    violationType: "Ponteng surau",
    demerit: -5,
    location: "Asrama",
    reportedBy: "Nizam",
    actionTaken: "Kaunseling",
    details: "Berlari dan betapuk sebab tidak mahu solat berjemaah",
    createdAt: 1739218140000
  },
  {
    id: "REC013",
    date: "2026-02-10",
    day: "Selasa",
    time: "20:10",
    studentName: "Mohd Khairil Faizi Bin Moktar",
    studentClass: "UMAR",
    category: "SALAH LAKU RINGAN",
    violationType: "Ponteng surau",
    demerit: -5,
    location: "Asrama",
    reportedBy: "Nizam",
    actionTaken: "Tiada tindakan khusus",
    details: "Tidur dan tidak ikut solat berjemaah",
    createdAt: 1739218200000
  }
];
